In [7]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.ndim

2

In [10]:
A = np.round(10*np.random.rand(5,4))
A

array([[ 3.,  6.,  1.,  7.],
       [ 8.,  1.,  1.,  5.],
       [ 2.,  3.,  6., 10.],
       [ 9., 10.,  5.,  4.],
       [ 6.,  9.,  3.,  7.]])

In [11]:
A[1,:]

array([8., 1., 1., 5.])

In [12]:
A[:,2]

array([1., 1., 6., 5., 3.])

In [13]:
A[1:3, 2:4]

array([[ 1.,  5.],
       [ 6., 10.]])

In [14]:
A[::2]

array([[ 3.,  6.,  1.,  7.],
       [ 2.,  3.,  6., 10.],
       [ 6.,  9.,  3.,  7.]])

In [15]:
import numpy.linalg as la

In [16]:
la.inv(np.random.rand(3,3))

array([[ 2.10856871, -1.93351437, -0.05008918],
       [-0.21333133, -0.72877513,  1.22398346],
       [-0.0626403 ,  1.22467173, -0.21066129]])

In [17]:
A.sort(axis=0)
A

array([[ 2.,  1.,  1.,  4.],
       [ 3.,  3.,  1.,  5.],
       [ 6.,  6.,  3.,  7.],
       [ 8.,  9.,  5.,  7.],
       [ 9., 10.,  6., 10.]])

In [18]:
A[1,2]

1.0

In [19]:
B = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
B

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
B[1, 1, 1]

5

In [21]:
B[(B<5) | (B>3)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
B.sort()
B

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
B = np.random.rand(10000000)
%timeit sum(B)
%timeit np.sum(B)

1.29 s ± 241 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
16.9 ms ± 1.37 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
def mySum(G):
  s = 0
  for x in G:
    s+=x
  return s

In [25]:
%timeit mySum(B)

2.82 s ± 164 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
import numpy as np

In [27]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [28]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [29]:
# Get Dimension
a.ndim

1

In [30]:
# Get Shape
b.shape

(2, 3)

In [31]:
# Get Type (datatype with bits)
a.dtype

dtype('int32')

In [32]:
# Change datatype
c = np.array([1,2,3], dtype="float32")
print(c)

[1. 2. 3.]


In [33]:
# Get Size in bytes
a.itemsize

4

In [34]:
# Get total size (number of elements)
b.size

6

In [35]:
# Get total number of bytes
b.nbytes

48

In [36]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
a.shape

(2, 7)

In [38]:
# Get a specific element [r, c]
a[1, 5]
#a[1, -2]

13

In [39]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [41]:
# Getting a little more fancy [Startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [42]:
# Update specific element
a[1,5] = 20
print(a)

# Update a specific column
a[:, 2] = 5
print(a)

a[:, 2] = [1, 3]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  3 11 12 20 14]]


# 3D Exmaples

In [43]:
b = np.array([[[1,2], [3,4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [45]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [46]:
#replace
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [47]:
# All 0s matrix
np.zeros(4)

array([0., 0., 0., 0.])

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [50]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [51]:
# Any other number ((r,c), number) 
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [52]:
# Any other number (full_like)
np.full_like(a, 4)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [53]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.3766693 , 0.12046147, 0.47546326],
        [0.32167597, 0.01152874, 0.37415727]],

       [[0.76668961, 0.90948131, 0.65785524],
        [0.29884545, 0.87002898, 0.82670252]],

       [[0.8697541 , 0.37832986, 0.16188211],
        [0.83181354, 0.97453594, 0.6361006 ]],

       [[0.54431562, 0.32776999, 0.8412969 ],
        [0.21712581, 0.43278852, 0.46766239]]])

In [54]:
np.random.random_sample(a.shape)

array([[0.02255   , 0.71770438, 0.14717786, 0.47021979, 0.7518082 ,
        0.99039319, 0.40672901],
       [0.65532578, 0.63492718, 0.35117818, 0.26202509, 0.38438758,
        0.94719021, 0.02828405]])

In [60]:
# Random Integer values (range, size)
np.random.randint(7, size=(3,3))

array([[4, 3, 0],
       [3, 2, 1],
       [0, 1, 4]])

In [64]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
# Repeat an array 0 = column wise, 1 = row wise
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [81]:
# Problem 1

# |1|1|1|1|1|
# |1|0|0|0|1|
# |1|0|9|0|1|
# |1|0|0|0|1|
# |1|1|1|1|1|

output = np.ones([5,5])
print(output)

z = np.zeros([3,3])
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays !!!

In [84]:
# Wrong method 
a = np.array([1,2,3])
b = a

b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [86]:
# Right method
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathmatics

In [101]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [99]:
a + 2

array([5, 6, 7, 8])

In [88]:
a - 2

array([-1,  0,  1,  2])

In [89]:
a * 2

array([2, 4, 6, 8])

In [90]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [108]:
b = np.array([1,0,1,0])
a * b

array([1, 0, 3, 0])

In [103]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [106]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [107]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [115]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [120]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Statistics

In [121]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
# Minimum element
np.min(stats)

1

In [136]:
# Maximum element
np.max(stats)

6

In [133]:
# Row basis
np.min(stats, axis=1)

np.max(stats, axis=1)

array([3, 6])

In [134]:
# Column basis
np.min(stats, axis=0)

np.max(stats, axis=0)
print(b)

[4 5 6]


In [138]:
# Sum of elements
np.sum(stats)

21

In [139]:
# Row basis sum
np.sum(stats, axis=1)

array([ 6, 15])

In [140]:
# Column basis sum
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [150]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [151]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontally stacking vectors

In [152]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# Miscellaneous
# Load Data from File

In [162]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32') #typecasting
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

# Boolean Masking and Advanced Indexing

In [163]:
filedata > 50 # Returns boolean value according to expression

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [164]:
filedata[filedata > 50] # Returns values according to expression

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [167]:
## Any element greater than 50 in column basis
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [168]:
## All element greater than 50 in column basis
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [178]:
filedata[(filedata > 50) & (filedata < 100)]

array([75, 75, 55, 78, 76, 88])

In [179]:
# '~' used as not operator 
filedata[~(filedata > 50) & (filedata < 100)]

array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1])

In [166]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [189]:
# Problem 2

# |01|02|03|04|05|
# |06|07|08|09|10|
# |11|12|13|14|15|
# |16|17|18|19|20|
# |21|22|23|24|25|
# |26|27|28|29|30|

mat = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,39]])
print(mat)

# Problem 2.1

# |11|12|
# |16|17|

submat = mat[2:4, 0:2]
print(submat)

# Problem 2.2

#   |2|
#     |8|
#       |14|
#          |20|

submat = mat[[0,1,2,3], [1,2,3,4]]
print(submat)

# Problem 2.3

# |04|05|
# |24|25|
# |29|30|

submat = mat[[0,4,5], 3:]
print(submat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 39]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 39]]
